<?php

/**
 * @file
 *
 */


function views_admintools_theme()
{

    return [
        'vat_area' => [
            'render element' => 'view',
            'template' => 'vat-area',
            'variables' => [
                'access' => [],
                'buttons' => [],
                'vocabularies' => [],
                'modal' => [],
                'content' => [],
                'look' => [],
                'group' => [],
            ],
        ],
    ];
}


function views_admintools_preprocess_page(&$variables)
{


}