<?php

use Drupal\views_admintools\Controller\ViewsAdmintoolsController;

/**
 * @file
 *
 */


function views_admintools_theme()
{
  return [
    'vat_area' => [
      'render element' => 'view',
      'template' => 'vat-area',
      'variables' => [
        'access' => [],
        'buttons' => [],
        'vocabularies' => [],
        'modal' => [],
        'content' => [],
        'look' => [],
        'options' => [],
        'defaults' => ViewsAdmintoolsController::getViewsDefaults()
      ],
    ],
    'icon_sets' => [
      'render element' => 'children',
      'template' => 'icon-sets',
      'variables' => [
        'icon_sets' => ViewsAdmintoolsController::getIconSets(),
      ]
    ],
  ];
}


